import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Sidebar } from '../components/layout/Sidebar';
import { Topbar } from '../components/layout/Topbar';
import { MobileNav } from '../components/layout/MobileNav';
import { useCivic } from '../context/CivicContext';
import {
  Upload,
  Camera,
  CheckCircle2,
  AlertTriangle,
  MapPin,
  ShieldCheck,
  ArrowRight,
  ArrowLeft,
  Loader2,
  FileCheck2,
  Sparkles
} from 'lucide-react';

export const ReportIssuePage = () => {
  const { anonSessionId, addIncident } = useCivic();
  const navigate = useNavigate();

  const [step, setStep] = useState(1);
  const [selectedPreset, setSelectedPreset] = useState(null);
  const [customFile, setCustomFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState(null);

  // AI Analysis state
  const [analyzing, setAnalyzing] = useState(false);
  const [analysisProgress, setAnalysisProgress] = useState(0);
  const [analysisStageText, setAnalysisStageText] = useState('');
  
  // Incident details generated by AI or adjusted by user
  const [reportData, setReportData] = useState({
    type: 'Pothole',
    severity: 'High',
    location: 'GT Road, near Rawatpur Crossing, Kanpur',
    coordinates: [26.4784, 80.3015],
    aiConfidence: 94,
    description: 'Deep road cavity observed on main eastbound lane, affecting two-wheeler traffic.'
  });

  const [createdIncidentId, setCreatedIncidentId] = useState(null);

  // Sample quick presets for easy presentation testing
  const samplePresets = [
    {
      title: 'Pothole on GT Road',
      type: 'Pothole',
      severity: 'Critical',
      location: 'GT Road, near Rawatpur Crossing, Kanpur',
      aiConfidence: 94,
      desc: 'Large crater-sized pothole occupying 60% of eastbound lane.',
      img: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="250" fill="%233A3D42"><rect width="400" height="250" fill="%23EFECE6"/><rect y="120" width="400" height="130" fill="%2327272A"/><ellipse cx="200" cy="185" rx="70" ry="30" fill="%23111213"/><text x="140" y="80" fill="%231C1D1F" font-family="sans-serif" font-weight="bold">SAMPLE POTHOLE</text></svg>'
    },
    {
      title: 'Garbage Dump on Mall Road',
      type: 'Garbage',
      severity: 'High',
      location: 'Mall Road, near Phool Bagh Gate 2, Kanpur',
      aiConfidence: 89,
      desc: 'Commercial waste accumulation spilling onto public walkway.',
      img: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="250" fill="%2365A30D"><rect width="400" height="250" fill="%23EFECE6"/><rect y="120" width="400" height="130" fill="%2327272A"/><path d="M150 150 L180 110 L240 100 L270 150 Z" fill="%2365A30D"/><text x="130" y="80" fill="%231C1D1F" font-family="sans-serif" font-weight="bold">SAMPLE GARBAGE</text></svg>'
    },
    {
      title: 'Waterlogging at Swaroop Nagar',
      type: 'Waterlogging',
      severity: 'Critical',
      location: 'Swaroop Nagar, Lane 3, Kanpur',
      aiConfidence: 96,
      desc: 'Stagnant stormwater blocking school access corridor.',
      img: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="250" fill="%233B82F6"><rect width="400" height="250" fill="%23EFECE6"/><ellipse cx="200" cy="180" rx="160" ry="40" fill="%233B82F6" opacity="0.8"/><text x="120" y="80" fill="%231C1D1F" font-family="sans-serif" font-weight="bold">SAMPLE WATERLOGGING</text></svg>'
    }
  ];

  const handleSelectPreset = (preset) => {
    setSelectedPreset(preset);
    setPreviewUrl(preset.img);
    setReportData({
      type: preset.type,
      severity: preset.severity,
      location: preset.location,
      coordinates: [26.4784, 80.3015],
      aiConfidence: preset.aiConfidence,
      description: preset.desc
    });
  };

  const handleFileUpload = (e) => {
    const file = e.target.files[0];
    if (file) {
      setCustomFile(file);
      setPreviewUrl(URL.createObjectURL(file));
      setSelectedPreset(null);
    }
  };

  // Step 2: Start simulated AI analysis
  const startAiAnalysis = () => {
    if (!previewUrl) return;
    setStep(2);
    setAnalyzing(true);
    setAnalysisProgress(0);

    const stages = [
      { pct: 25, text: "Reviewing evidence photograph..." },
      { pct: 50, text: "Identifying civic defect classification..." },
      { pct: 75, text: "Estimating severity & volume..." },
      { pct: 100, text: "Checking geotag & spatial location..." }
    ];

    let index = 0;
    const interval = setInterval(() => {
      if (index < stages.length) {
        setAnalysisProgress(stages[index].pct);
        setAnalysisStageText(stages[index].text);
        index++;
      } else {
        clearInterval(interval);
        setAnalyzing(false);
      }
    }, 700);
  };

  const handleSubmitReport = () => {
    const created = addIncident({
      type: reportData.type,
      location: reportData.location,
      severity: reportData.severity,
      aiConfidence: reportData.aiConfidence,
      description: reportData.description,
      evidenceUrl: previewUrl || samplePresets[0].img
    });
    setCreatedIncidentId(created.id);
    setStep(5);
  };

  return (
    <div className="flex h-screen bg-[#FBF9F5] overflow-hidden">
      
      <div className="hidden md:block h-full">
        <Sidebar />
      </div>

      <div className="flex-1 flex flex-col min-w-0 h-full overflow-hidden">
        
        <Topbar title="Report Civic Issue" />

        <main className="flex-1 overflow-y-auto p-4 sm:p-6 pb-20 md:pb-6 max-w-4xl mx-auto w-full space-y-6">
          
          {/* Progress Step Header */}
          <div className="p-4 bg-white rounded-lg border border-[#EAE7DF] shadow-subtle">
            <div className="flex items-center justify-between text-xs font-bold text-charcoal mb-3">
              <span>REPORTING PIPELINE</span>
              <span className="font-mono text-civic">STEP {step} OF 5</span>
            </div>

            <div className="grid grid-cols-5 gap-2">
              {['1. Evidence', '2. AI Scan', '3. Location', '4. Review', '5. Submitted'].map((sName, i) => (
                <div key={i} className="space-y-1">
                  <div className={`h-1.5 rounded-full transition-colors ${
                    step > i + 1 ? 'bg-emerald-600' : step === i + 1 ? 'bg-civic' : 'bg-canvas-muted'
                  }`} />
                  <span className={`text-[10px] font-semibold block truncate ${
                    step === i + 1 ? 'text-civic' : 'text-charcoal-subtle'
                  }`}>
                    {sName}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* STEP 1: ADD EVIDENCE */}
          {step === 1 && (
            <div className="p-6 bg-white rounded-lg border border-[#EAE7DF] shadow-subtle space-y-6">
              <div>
                <h3 className="text-xl font-extrabold text-charcoal tracking-tight">
                  Step 1: Add Photo or Video Evidence
                </h3>
                <p className="text-xs text-charcoal-muted mt-1">
                  Upload a photo from your device or pick a preset sample photo for quick hackathon testing.
                </p>
              </div>

              {/* Upload Dropzone */}
              <div className="border-2 border-dashed border-[#EAE7DF] rounded-lg p-8 text-center hover:border-civic transition-colors bg-[#FAF9F5]">
                <input
                  type="file"
                  accept="image/*,video/*"
                  onChange={handleFileUpload}
                  className="hidden"
                  id="evidence-file-input"
                />
                <label htmlFor="evidence-file-input" className="cursor-pointer block space-y-3">
                  <div className="w-12 h-12 rounded-full bg-civic-light text-civic mx-auto flex items-center justify-center">
                    <Upload className="w-6 h-6" />
                  </div>
                  <div>
                    <span className="text-sm font-bold text-charcoal block">Click to upload photo or video</span>
                    <span className="text-xs text-charcoal-subtle">PNG, JPG, MP4 up to 50MB</span>
                  </div>
                </label>
              </div>

              {/* Sample Presets for presentation testing */}
              <div className="space-y-3 pt-2 border-t border-[#EAE7DF]">
                <span className="text-xs font-bold uppercase tracking-wider text-charcoal-subtle block">
                  Or select sample test evidence:
                </span>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                  {samplePresets.map((preset, idx) => (
                    <div
                      key={idx}
                      onClick={() => handleSelectPreset(preset)}
                      className={`p-3 rounded-lg border cursor-pointer transition-all ${
                        selectedPreset?.title === preset.title
                          ? 'border-civic bg-blue-50/30 ring-1 ring-civic'
                          : 'border-[#EAE7DF] bg-[#FAF9F5] hover:border-charcoal-subtle'
                      }`}
                    >
                      <span className="font-bold text-xs text-charcoal block mb-1">{preset.title}</span>
                      <span className="text-[10px] text-charcoal-muted block">{preset.type} • {preset.severity}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Selected Preview & Next Action */}
              {previewUrl && (
                <div className="p-4 rounded-lg bg-[#FAF9F5] border border-[#EAE7DF] space-y-4">
                  <div className="flex items-center justify-between text-xs">
                    <span className="font-bold text-charcoal">Selected Evidence Preview</span>
                    <span className="text-emerald-700 font-semibold text-[11px]">Ready for AI scan</span>
                  </div>
                  <img src={previewUrl} alt="Evidence preview" className="w-full h-48 object-cover rounded border border-[#EAE7DF]" />
                </div>
              )}

              <div className="flex justify-end pt-4 border-t border-[#EAE7DF]">
                <button
                  disabled={!previewUrl}
                  onClick={startAiAnalysis}
                  className="px-6 py-3 rounded-md text-xs font-bold text-white bg-charcoal hover:bg-civic disabled:bg-stone-300 disabled:cursor-not-allowed transition-colors shadow-subtle flex items-center space-x-2"
                >
                  <Sparkles className="w-4 h-4 text-amber-400" />
                  <span>Analyze Evidence with AI</span>
                </button>
              </div>
            </div>
          )}

          {/* STEP 2: SIMULATED AI ANALYSIS */}
          {step === 2 && (
            <div className="p-6 bg-white rounded-lg border border-[#EAE7DF] shadow-subtle space-y-6">
              <div>
                <h3 className="text-xl font-extrabold text-charcoal tracking-tight flex items-center space-x-2">
                  <Sparkles className="w-5 h-5 text-civic" />
                  <span>Step 2: AI Civic Analysis</span>
                </h3>
                <p className="text-xs text-charcoal-muted mt-1">
                  Computer vision model reviewing defect geometry, severity, and classification.
                </p>
              </div>

              {analyzing ? (
                <div className="py-12 text-center space-y-6">
                  <Loader2 className="w-12 h-12 text-civic animate-spin mx-auto" />
                  <div className="max-w-xs mx-auto space-y-2">
                    <span className="text-sm font-bold text-charcoal block">{analysisStageText}</span>
                    <div className="w-full bg-canvas-muted rounded-full h-2 overflow-hidden">
                      <div className="bg-civic h-2 rounded-full transition-all duration-300" style={{ width: `${analysisProgress}%` }} />
                    </div>
                    <span className="font-mono text-xs font-bold text-charcoal-subtle">{analysisProgress}% Complete</span>
                  </div>
                </div>
              ) : (
                <div className="space-y-6 animate-slide-up">
                  <div className="p-4 rounded-lg bg-emerald-50 border border-emerald-200 flex items-start space-x-3">
                    <CheckCircle2 className="w-5 h-5 text-emerald-700 shrink-0 mt-0.5" />
                    <div>
                      <span className="font-bold text-sm text-emerald-900 block">AI Classification Complete</span>
                      <p className="text-xs text-emerald-800 mt-0.5">
                        Defect identified with {reportData.aiConfidence}% confidence match.
                      </p>
                    </div>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div className="p-4 rounded-lg bg-[#FAF9F5] border border-[#EAE7DF] space-y-2">
                      <span className="text-[11px] font-bold text-charcoal-subtle uppercase tracking-wider block">Identified Type</span>
                      <span className="text-lg font-bold text-charcoal block">{reportData.type}</span>
                    </div>

                    <div className="p-4 rounded-lg bg-[#FAF9F5] border border-[#EAE7DF] space-y-2">
                      <span className="text-[11px] font-bold text-charcoal-subtle uppercase tracking-wider block">Severity Score</span>
                      <span className="text-lg font-bold text-red-600 block">{reportData.severity} Severity</span>
                    </div>
                  </div>

                  <div className="flex justify-between pt-4 border-t border-[#EAE7DF]">
                    <button
                      onClick={() => setStep(1)}
                      className="px-4 py-2 rounded-md text-xs font-semibold text-charcoal-muted hover:bg-canvas-subtle"
                    >
                      ← Re-upload
                    </button>
                    <button
                      onClick={() => setStep(3)}
                      className="px-6 py-2.5 rounded-md text-xs font-bold text-white bg-charcoal hover:bg-civic transition-colors shadow-subtle flex items-center space-x-2"
                    >
                      <span>Adjust Location</span>
                      <ArrowRight className="w-4 h-4" />
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* STEP 3: LOCATION ADJUSTMENT */}
          {step === 3 && (
            <div className="p-6 bg-white rounded-lg border border-[#EAE7DF] shadow-subtle space-y-6">
              <div>
                <h3 className="text-xl font-extrabold text-charcoal tracking-tight">
                  Step 3: Location & Geotag Confirmation
                </h3>
                <p className="text-xs text-charcoal-muted mt-1">
                  Ensure the location accurately reflects the incident site.
                </p>
              </div>

              <div className="space-y-4">
                <div>
                  <label className="text-xs font-bold text-charcoal block mb-1">Detected Location Landmark</label>
                  <div className="flex items-center space-x-2">
                    <MapPin className="w-4 h-4 text-civic shrink-0" />
                    <input
                      type="text"
                      value={reportData.location}
                      onChange={(e) => setReportData({ ...reportData, location: e.target.value })}
                      className="flex-1 text-xs font-semibold p-2.5 rounded border border-[#EAE7DF] bg-[#FAF9F5]"
                    />
                  </div>
                </div>

                <div>
                  <label className="text-xs font-bold text-charcoal block mb-1">Description & Field Notes</label>
                  <textarea
                    rows={3}
                    value={reportData.description}
                    onChange={(e) => setReportData({ ...reportData, description: e.target.value })}
                    className="w-full text-xs font-medium p-2.5 rounded border border-[#EAE7DF] bg-[#FAF9F5]"
                  />
                </div>
              </div>

              <div className="flex justify-between pt-4 border-t border-[#EAE7DF]">
                <button
                  onClick={() => setStep(2)}
                  className="px-4 py-2 rounded-md text-xs font-semibold text-charcoal-muted hover:bg-canvas-subtle"
                >
                  ← Back
                </button>
                <button
                  onClick={() => setStep(4)}
                  className="px-6 py-2.5 rounded-md text-xs font-bold text-white bg-charcoal hover:bg-civic transition-colors shadow-subtle flex items-center space-x-2"
                >
                  <span>Review Anonymous Report</span>
                  <ArrowRight className="w-4 h-4" />
                </button>
              </div>
            </div>
          )}

          {/* STEP 4: REVIEW ANONYMOUS REPORT */}
          {step === 4 && (
            <div className="p-6 bg-white rounded-lg border border-[#EAE7DF] shadow-subtle space-y-6">
              <div>
                <h3 className="text-xl font-extrabold text-charcoal tracking-tight">
                  Step 4: Review Anonymous Report
                </h3>
                <p className="text-xs text-charcoal-muted mt-1">
                  Your identity is protected under NagarSetu privacy protocol.
                </p>
              </div>

              <div className="p-4 rounded-lg bg-emerald-50 border border-emerald-200 flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <ShieldCheck className="w-6 h-6 text-emerald-700" />
                  <div>
                    <span className="font-bold text-sm text-emerald-900 block">Privacy Protection Active</span>
                    <span className="text-xs text-emerald-800">Reporter: Anonymous Citizen ({anonSessionId})</span>
                  </div>
                </div>
                <span className="text-[10px] font-mono font-bold bg-white text-emerald-800 px-2 py-1 rounded border border-emerald-300">
                  NO PII STORED
                </span>
              </div>

              <div className="p-4 rounded-lg bg-[#FAF9F5] border border-[#EAE7DF] space-y-3 text-xs">
                <div className="flex justify-between border-b border-[#EAE7DF] pb-2">
                  <span className="text-charcoal-subtle">Issue Type</span>
                  <span className="font-bold text-charcoal">{reportData.type}</span>
                </div>
                <div className="flex justify-between border-b border-[#EAE7DF] pb-2">
                  <span className="text-charcoal-subtle">Severity</span>
                  <span className="font-bold text-red-600">{reportData.severity}</span>
                </div>
                <div className="flex justify-between border-b border-[#EAE7DF] pb-2">
                  <span className="text-charcoal-subtle">Location</span>
                  <span className="font-bold text-charcoal">{reportData.location}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-charcoal-subtle">AI Confidence</span>
                  <span className="font-mono font-bold text-charcoal">{reportData.aiConfidence}%</span>
                </div>
              </div>

              <div className="flex justify-between pt-4 border-t border-[#EAE7DF]">
                <button
                  onClick={() => setStep(3)}
                  className="px-4 py-2 rounded-md text-xs font-semibold text-charcoal-muted hover:bg-canvas-subtle"
                >
                  ← Edit Details
                </button>
                <button
                  onClick={handleSubmitReport}
                  className="px-8 py-3 rounded-md text-xs font-bold text-white bg-charcoal hover:bg-civic transition-colors shadow-modal flex items-center space-x-2"
                >
                  <FileCheck2 className="w-4 h-4 text-emerald-400" />
                  <span>Submit Anonymous Report</span>
                </button>
              </div>
            </div>
          )}

          {/* STEP 5: SUBMITTED SUCCESS */}
          {step === 5 && (
            <div className="p-8 bg-white rounded-lg border border-[#EAE7DF] shadow-modal text-center space-y-6 animate-slide-up">
              <div className="w-16 h-16 rounded-full bg-emerald-100 text-emerald-700 flex items-center justify-center mx-auto">
                <CheckCircle2 className="w-10 h-10" />
              </div>

              <div>
                <span className="text-xs font-mono font-bold text-civic bg-civic-light px-2.5 py-1 rounded">
                  INCIDENT REGISTERED
                </span>
                <h3 className="text-2xl font-extrabold text-charcoal tracking-tight mt-3">
                  {createdIncidentId} Created Successfully
                </h3>
                <p className="text-xs text-charcoal-muted mt-1 max-w-md mx-auto">
                  Your report has been broadcast to nearby opted-in citizens for neighborhood verification.
                </p>
              </div>

              <div className="p-4 rounded-lg bg-[#FAF9F5] border border-[#EAE7DF] text-xs max-w-md mx-auto text-left space-y-2">
                <div className="flex justify-between">
                  <span className="text-charcoal-subtle">Category</span>
                  <span className="font-bold text-charcoal">{reportData.type}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-charcoal-subtle">Location</span>
                  <span className="font-bold text-charcoal">{reportData.location}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-charcoal-subtle">AI Match Confidence</span>
                  <span className="font-mono font-bold text-charcoal">{reportData.aiConfidence}%</span>
                </div>
              </div>

              <div className="flex flex-wrap items-center justify-center gap-3 pt-4 border-t border-[#EAE7DF]">
                <button
                  onClick={() => navigate(`/incident/${createdIncidentId}`)}
                  className="px-6 py-2.5 rounded-md text-xs font-bold text-white bg-charcoal hover:bg-civic transition-colors shadow-subtle"
                >
                  View Incident Details
                </button>
                <button
                  onClick={() => navigate('/community')}
                  className="px-6 py-2.5 rounded-md text-xs font-bold text-charcoal bg-[#FAF9F5] border border-[#EAE7DF] hover:bg-canvas-subtle"
                >
                  Verify Neighborhood Issues
                </button>
              </div>
            </div>
          )}

        </main>

      </div>

      <MobileNav />
    </div>
  );
};
